
export const receitas = [
	{
		id: 1,
		name: "Burrata com tomate confit e pesto",
		category: "Entrada",
		tempoPreparo: "30 min",
		image: "burrata",
		ingredientes: [
			"Queijo burrata a gosto",
			"200 gramas de tomate-cereja",
			"3 dentes de alho laminado",
			"2 ramos grandes de alecrim, ou tomilho, ou orégano, ou sálvia (ou mix dos quatro)",
			"30 gramas de parmesão",
			"30 gramas de nozes",
			"1/2 dente de alho",
			"Sal a gosto",
			"Azeite a gosto",
			"Pimenta-do-reino a gosto",
			"Manjericão a gosto",
		],
		modo_de_preparo: [
			"Reúna todos os ingredientes",
			"Coloque os tomates-cereja em uma forma que possa ir ao forno. Cubra com azeite",
			"Tempere com sal, pimenta, alho laminado e as ervas selecionadas",
			"Asse em forno preaquecido a 160 ºC por cerca de 20 minutos",
			"Em um pilão, misture o parmesão, as nozes, o manjericão, o alho, sal e azeite",
			"Amasse até obter uma pasta",
			"Coloque os tomatinhos com um pouco do azeite em um prato fundo",
			"Por cima arrume o queijo burrata",
			"Finalize com o molho pesto e sirva-se.",
		],
		id_video: "FTVLB1Vofbs",
	},
	{
		id: 2,
		name: "Canapés de ricota com azeitona",
		category: "Entrada",
		tempoPreparo: "1h45 min",
		image: "canapeRicota",
		ingredientes: [
			"250 gramas de farinha de trigo⁣",
			"100 gramas de margarina⁣",
			"1 pitada de sal⁣",
			"50 ml de água gelada",
			"300 gramas de ricota⁣",
			"160 gramas de azeitona sem caroço",
			"Azeite a gosto⁣",
			"Pimenta-do-reino a gosto⁣",
		],
		modo_de_preparo: [
			"Misture a farinha, a margarina e o sal.",
			"Adicione água aos poucos até ficar macio e com boa consistência.",
			"Cubra e leve para geladeira por 1 hora.",
			"Abra com um rolo e corte círculos.",
			"Molde em forminhas de canapé.",
			"Asse por 14 minutos a 200 °C. Deixe esfriar.",
			"Misture todos os ingredientes no processador e adicione o azeite gradualmente.",
			"O ponto ideal é uma pasta homogênea.",
			"Coloque em um bico de confeitar e coloque sobre as cestinhas.",
			"Agora é só servir",
		],
		id_video: "Bhfa2Pp4KOg",
	},
	{
		id: 3,
		name: "Canapés de pão de queijo",
		category: "Entrada",
		tempoPreparo: "1h10 min",
		image: "canapePao",
		ingredientes: [
			"14 pães de queijo congelados",
			"150 gramas de peito de peru",
			"80 gramas de ricota",
			"1 colher de sopa de maionese",
			"4 colheres de sopa de creme de leite",
			"Sal a gosto",
			"Pimenta-do-reino a gosto",
			"Pontas de cebolinha picada a gosto",
			"2 damascos desidratados",
		],
		modo_de_preparo: [
			"Asse os pães de queijo no forno a 180 °C por cerca de 40 minutos.",
			"Enquanto isso, coloque no processador o peito de peru com ricota, maionese, creme de leite, sal e pimenta-do-reino.",
			"Bata tudo até obter uma textura de pasta.",
			"Reserve na geladeira por 20 minutos.",
			"Retire os pães de queijo do forno e corte-os ao meio.",
			"Com os pães de queijo abertos, coloque o patê por cima de cada metade.",
			"Corte os damascos em cubinhos e decore os canapés polvilhando por cima do patê.",
			"Finalize decorando com as pontas de cebolinha.",
			"Agora é só servir",
		],
		id_video: "7Nhm9u9H-eU",
	},
	{
		id: 5,
		name: "Picanha na manteiga",
		category: "Prato principal",
		tempoPreparo: "30 min",
		image: "picanha",
		ingredientes: [
			"1 kg de picanha",
			"1 tablete de manteiga de leite",
			"10 dentes de alho",
			"1 colher de chá de pimenta calabresa",
			"4 colheres de sopa de sal grosso",
			"500 gramas macaxeira",
		],
		modo_de_preparo: [
			"Disponha a carne em um refratário. Espalhe os dentes de alho na picanha inteira.",
			"Tempere-a com sal grosso e adicione a manteiga sobre a carne e leve para assar a 200 °C por 30 minutos.",
			"Passado o tempo, vire a picanha do outro lado, regando-a com mais manteiga e acrescente a macaxeira.",
			"Vire a picanha por mais duas vezes até ela estar bem frita na manteiga.",
			"Agora é só servir! Bom apetite.",
		],
		id_video: "Nw8M5GzoNo0",
	},
	{
		id: 6,
		name: "Arroz com frango e açafrão",
		category: "Prato principal",
		tempoPreparo: "30 min",
		image: "arrozFrango",
		ingredientes: [
			"2 colheres de sopa de azeite",
			"1 cebola grande cortada em cubos",
			"2 xícaras de chá de arroz cru",
			"2 xícaras de chá de caldo de legumes",
			"2 xícaras de chá de água",
			"1 colher de sopa rasa de açafrão em pó (ou cúrcuma)",
			"½ kg de peito de frango cozido, temperado e desfiado",
			"1 xícara de chá de palmito picado",
			"Sal a gosto",
			"Cebolinha a gosto",
		],
		modo_de_preparo: [
			"Reúna todos os ingredientes;",
			"Leve uma panela ao fogo médio, esquente o azeite e refogue a cebola;",
			"Assim que ela começar a murchar, junte o arroz, o caldo de legumes, a água, o açafrão e misture;",
			"Quando o arroz começar a ferver, acrescente o frango desfiado, o palmito e acerte o sal;",
			"Tampe a panela e deixe os ingredientes cozinharem até a água secar;",
			"Depois, desligue o fogo, salpique cebolinha e sirva.",
		],
		id_video: "o7giyzF1jDw",
	},
	{
		id: 7,
		name: "Arroz cremoso de camarão",
		category: "Prato principal",
		tempoPreparo: "30 min",
		image: "arrozCamarao",
		ingredientes: [
			"Azeite a gosto",
			"400 g de camarão descascado",
			"Sal a gosto",
			"Pimenta-do-reino a gosto",
			"2 dentes de alho",
			"1 tomate",
			"2 colheres de sopa de extrato de tomate",
			"1/2 colher de chá de páprica picante",
			"200 g de creme de leite fresco",
			"1/2 xícara de chá de requeijão",
			"1 xícara de chá de arroz cozido",
			"100 g de queijo ralado",
		],
		modo_de_preparo: [
			"Em uma frigideira, coloque o azeite, o camarão e tempere com sal e pimenta.",
			"Doure o camarão e reserve.",
			"Na mesma frigideira, coloque mais azeite, o alho, o tomate e refogue por dois minutos.",
			"Adicione o extrato de tomate, a páprica e coloque o camarão.",
			"Junte o creme de leite e deixe cozinhar por alguns minutos.",
			"Em um refratário, coloque o requeijão, o arroz cozido e misture bem.",
			"Coloque por cima o molho de camarão, o queijo ralado e leve para assar em forno preaquecido a 180°C por vinte minutos.",
		],
		id_video: "Pn0DQRQ_ctI",
	},
	{
		id: 8,
		name: "Filé mignon com molho de vinho tinto",
		category: "Prato principal",
		tempoPreparo: "40 min",
		image: "fileMignon",
		ingredientes: [
			"4 tornedores (corte com o dobro de tamanho do medalhão) de filé mignon com 3 dedos de espessura",
			"Sal e pimenta a gosto",
			"1 colher de sobremesa de manteiga",
			"1 cebola média ralada",
			"100ml de vinho tinto",
			"200ml de caldo de verdura",
			"1 colher de sobremesa rasa de amido de milho",
			"1 fatia fina e comprida de bacon",
			"1 colher de sopa de manteiga",
		],
		modo_de_preparo: [
			"Reúna todos os ingredientes;",
			"Tempere a carne com sal, pimenta e reserve;",
			"Em uma panela, derreta a manteiga (1 colher de sobremesa) e refogue a cebola até ela dourar e secar um pouco da água;",
			"Adicione o vinho e deixe reduzir (cerca de 5 minutos);",
			"Misture o caldo de legumes com o amido, para dissolver bem;",
			"Despeje na panela, misture e deixe o molho engrossar;",
			"Coloque o sal, a pimenta, misture bem e desligue o fogo. Peneire o molho para retirar o excesso de cebola (caso queira). Reserve;",
			"Em uma frigideira, em fogo alto, adicione a fatia de bacon e deixe fritar;",
			"Assim que começar a fritar e soltar a gordura, acrescente a manteiga (colher de sopa) e deixe derreter;",
			"Reserve o bacon, coloque os filés e deixe fritar dos dois lados (cerca de 5 minutos de cada lado);",
			"Quando estiverem prontos, transfira-os para uma travessa;",
			"Junte quase toda a manteiga derretida com a gordura do bacon, na panela com o molho. Ligue o fogo, misture e deixe esquentar um pouco;",
			"Acerte o sal, despeje o molho por cima dos filés e sirva.",
		],
		id_video: "SQ_NRXQ7xHE ",
	},
	{
		id: 9,
		name: "Moqueca de palmito pupunha",
		category: "Vegano",
		tempoPreparo: "35 min",
		image: "moqueca",
		ingredientes: [
			"3 colheres de sopa de azeite",
			"½ cebola em cubos",
			"2 dentes de alho picados",
			"½ pimentão amarelo em cubos",
			"1 tomate em cubos",
			"Sal a gosto",
			"240 ml de leite de coco",
			"Coentro a gosto",
			"1 pimentão amarelo em fatias",
			"3 tomates em fatias",
			"2 vidros de palmito pupunha",
		],
		modo_de_preparo: [
			"Em uma panela, refogue a cebola e o alho no azeite.",
			"Adicione o tomate e o pimentão em cubos.",
			"Tempere com sal e deixe cozinhar por cerca de 10 minutos.",
			"Acrescente o leite de coco e o coentro.",
			"Cozinhe por mais alguns minutos.",
			"Coloque uma camada de pimentão em fatias, outra de tomates fatiados e uma de palmito.",
			"Repita as camadas e tampe.",
			"Deixe cozinhar por cerca de 15 minutos.",
			"Finalize com folhas de coentro e sirva-se.",
		],
		id_video: "S3q5x9fPHpQ ",
	},
	{
		id: 10,
		name: "Risoto vegano",
		category: "Vegano",
		tempoPreparo: "20 min",
		image: "risotoVegano",
		ingredientes: [
			"1 cebola média picada",
			"3 colheres de sopa de azeite",
			"1 xícara de chá de arroz arbóreo ou cateto cru",
			"1/2 xícara de chá de vinho branco seco",
			"3 xícaras de caldo de legumes",
			"1/2 xícara de queijo vegano relado ou requeijão de castanha",
			"1 colher de chá de cúrcuma em pó",
			"2 colheres de chá de sal",
			"Alecrim a gosto",
			"Pimenta-do-reino a gosto",
		],
		modo_de_preparo: [
			"Em uma panela a fogo baixo, coloque o azeite e a cebola para refogar, até que fique transparente.",
			"Junte o arroz e misture bem.",
			"Acrescente o vinho e mexa, mantendo o fogo baixo, e deixe dar uma reduzida.",
			"Em seguida, adicione uma concha de caldo de legumes e misture sempre, para não grudar ao fundo. Quando o líquido estiver quase secando, repita o processo, mexendo sem parar, até que acabe o caldo e o arroz fiqueal dente.",
			"Tempere com sal, a cúrcuma, o queijo, pimenta-do-reino e alecrim, mexendo bem e constantemente.",
			"Tampe a panela e deixe cozinhar por uns 2 minutos.",
			"Agora é só servir!",
		],
		id_video: "WThvrmplkyc ",
	},
	{
		id: 11,
		name: "Torta de liquidificador vegana",
		category: "Vegano",
		tempoPreparo: "30 min",
		image: "torta",
		ingredientes: [
			"1 colher de sopa de azeite de oliva",
			"1 cebola cortada em cubos",
			"1 dente de alho picado",
			"1 cenoura cortada em cubos",
			"1 tomate sem casca cortado em cubos",
			"1/2 xícara de chá de ervilha",
			"1 xícara de chá de milho",
			"1 colher de chá sal",
			"1 colher de café de páprica defumada",
			"1/2 xícara de chá de azeitonas picadas",
			"Pimenta-do-reino a gosto",
			"1/3 de xícara de chá de óleo de girassol",
			"1/2 cebola cortada",
			"1 colher de chá sal",
			"1 xícara de chá de água",
			"1 colher de café de cúrcuma",
			"1 e 1/2 xícara de chá de farinha de trigo",
			"1/2 colher de sopa fermento",
			"Orégano a gosto",
		],
		modo_de_preparo: [
			"Reúna todos os ingredientes;",
			"Leve uma panela ao fogo, adicione o azeite, e refogue a cebola;",
			"Acrescente o alho e a cenoura, e refogue por mais 3 minutos;",
			"Junte o tomate, a ervilha, o milho, o sal, a páprica, as azeitonas, a pimenta refogue tudo por 5 minutos, e reserve;",
			"Reúna todos os ingredientes;",
			"Coloque o óleo, a cebola, o sal, a água e a cúrcuma no liquidificador, e bata;",
			"Acrescente a farinha e bata até homogeneizar;",
			"Adicione o fermento e misture com uma colher até ele se incorporar;",
			"Despeje metade da massa em uma forma untada, espalhe o recheio por cima, e cubra-o com a outra metade da massa; depois, salpique orégano e pedacinhos de azeitonas;",
			"Asse a torta em forno preaquecido a 180º graus por cerca de 35 minutos;",
			"Agora é só servir.",
		],
		id_video: "WThvrmplkyc ",
	},
	{
		id: 12,
		name: "Hossomaki de pepin",
		category: "Vegano",
		tempoPreparo: "50 min",
		image: "Hossomaki",
		ingredientes: [
			"1 xícara de chá de arroz para sushi (grão curto)",
			"1 e 1/4 de xícara de chá de água fria",
			"1 colher chá de sal",
			"2 colheres de sopa de vinagre de arroz",
			"1 colher de sopa de açúcar",
			"1 pepino-japonês",
			"1 folha de alga nori",
		],
		modo_de_preparo: [
			"Reúna todos os ingredientes.",
			"Higienize bem o arroz com água e o deixe descansar por 30 minutos.",
			"Transfira para uma panela, adicione a água, o sal, tampe, ligue o fogo médio e deixe cozinhar até a água começar a ferver.",
			"Aumente o fogo e deixe ferver por 1 minuto.",
			"Diminua o fogo e deixe cozinhar por 15 minutos.",
			"Desligue e deixe descansar por 10 minutos ainda com a panela tampada.",
			"Em outra panela, coloque o vinagre, o açúcar, misture e leve ao fogo baixo até o açúcar se dissolver.",
			"Transfira o arroz para uma forma, despeje a mistura de vinagre sobre ele e misture com cuidado.",
			"Deixe o arroz esfriar e reserve.",
			"Corte o pepino em tirinhas na vertical e retire as sementes.",
			"Disponha o nori em uma esteira de bambu",
			"Umedeça as mãos com água, pegue uma porção do arroz e molde em formato de uma bola do tamanho de um limão e coloque no centro do nori.",
			"Espalhe bem sobre a alga, deixando cerca de 2 centímetros de borda e coloque as tirinhas do pepino no centro do arroz.",
			"Umedeça a borda com água, enrole com cuidado, formando um rolinho e pressionando delicadamente.",
			"Retire a esteira e corte rodelas com uma faca umedecida com água.",
			"Agora é só servir",
		],
		id_video: "eGWhdkIMKhQ ",
	},
	{
		id: 13,
		name: "Mousse de leite Ninho",
		category: "Sobremesas",
		tempoPreparo: "4h10 min",
		image: "mousseLeite",
		ingredientes: [
			"1 lata de leite condensado",
			"2 caixinhas de creme de leite (400 gramas)",
			"1 e 1/2 xícara de chá de leite Ninho",
		],
		modo_de_preparo: [
			"Reúna todos os ingredientes;",
			"Coloque tudo no liquidificador e bata até misturar bem e ficar homogêneo (cerca de 3 a 5 minutos);",
			"Transfira para um refratário e leve para a geladeira por no mínimo 4 horas;",
			"Decore com frutas ou raspas de chocolate e sirva.",
		],
		id_video: "-AdP9roAPao ",
	},
	{
		id: 14,
		name: "Mousse de limão",
		category: "Sobremesa",
		tempoPreparo: "20 min",
		image: "mousseLimao",
		ingredientes: [
			"1 lata de creme de leite",
			"1 lata de leite condensado",
			"½ xícara de chá de suco de limão",
		],
		modo_de_preparo: [
			"Reúna todos os ingredientes;",
			"Coloque o creme de leite e o leite condensado no liquidificador e bata;",
			"Gradualmente, acrescente o suco de limão;",
			"Quando a mistura começar a ganhar consistência, desligue o liquidificador, transfira-a para uma vasilha, leve à geladeira, espere gelar e sirva na sequência;",
		],
		id_video: "DCvBg7dr5bM ",
	},
	{
		id: 15,
		name: "Mousse de milho verde com goiabada",
		category: "Sobremesa",
		tempoPreparo: "1hr10 min",
		image: "mousseMilho",
		ingredientes: [
			"1 sachê de gelatina sem sabor",
			"1 lata de milho verde em conserva",
			"1 lata de leite condensado",
			"1 caixinha de creme de leite",
			"200 g de goiabada",
			"1/2 copo de água (ou até dar o ponto de calda)",
		],
		modo_de_preparo: [
			"Hidrate a gelatina conforme as instruções do fabricante.",
			"Em um liquidificador, adicione o milho escorrido, o leite condensado, o creme de leite e a gelatina hidratada. Bata por cerca de 5 minutos e reserve.",
			"Em uma panela, coloque a goiabada e a água e derreta até formar uma calda.",
			"Desligue o fogo e deixe esfriar completamente.",
			"Em um refratário ou em taças, forre o fundo com um pouco da calda de goiabada e leve para a geladeira por alguns minutos.",
			"Com cuidado, despeje a mousse por cima, decore com o restante da calda e leve para a geladeira por 1h no mínimo.",
			"Agora é só servir. Bom apetite.",
		],
		id_video: "e19wM-9aB9w",
	},
	{
		id: 16,
		name: "Creme de ganache de chocolate",
		category: "Sobremesa",
		tempoPreparo: "10 min",
		image: "ganache",
		ingredientes: [
			"300 gramas de nata",
			"100 ml de creme de leite",
			"3 colheres de sopa de adoçante",
			"1 colher de café de essência de baunilha⁣",
			"100 gramas de chocolate 70%",
			"100 ml de creme de leite",
			"2 colheres de café de adoçante",
		],
		modo_de_preparo: [
			"Em um liquidificador, coloque a nata, o creme de leite, o adoçante, a baunilha e bata bem.",
			"Em uma travessa, coloque o chocolate, o creme de leite, o adoçante e leve para derreter em banho-maria.",
			"Coloque o creme de nata em tacinhas e a ganache por cima.",
			"Finalize com amêndoas em lascas, chocolate 70% ralado, nibs de cacau ou xerém de castanha de caju.",
			"Agora é só servir! Bom apetite.",
		],
		id_video: "LPPPwpAfk50 ",
	},
];
  